# name: Daily Stock Run

# on:
#   schedule:
#     - cron: '0 18 * * *' # 1 AM UTC+7
#   workflow_dispatch:

# jobs:
#   run-scripts:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout repo
#         uses: actions/checkout@v4

#       - name: Set up Python
#         uses: actions/setup-python@v5
#         with:
#           python-version: '3.12.10'

#       - name: Install dependencies
#         run: |
#           python -m pip install --upgrade pip
#           pip install -r python/requirements.txt

#       - name: Run getter.py
#         run: python python/getter.py

#       - name: Run logiczer.py
#         run: python python/logiczer.py
